openapi: 3.0.0
info:
  title: Biiiiip API sepc
  version: '0.1'
  description: ''
servers:
  - url: 'https://{biiiiip.server}'
paths:
  /applySwitching:
    post:
      summary: Apply for switch service
      operationId: post-switching-application-form
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                supplyPointNumber:
                  type: string
                  description: 供給地点特定番号
                  pattern: '^[0-9]{22,}$'
                retailerCode:
                  type: string
                  description: 小売事業者コード
                  pattern: '^[a-zA-Z0-9]{5,}$'
                retailerName:
                  type: string
                  description: 小売事業者名称
                  maxLength: 50
                loginUserId:
                  type: string
                  pattern: '^[a-zA-Z0-9]{7,}$'
                  description: ログインユーザID
                retailerStaff:
                  type: string
                  description: 小売事業者担当者氏名
                  maxLength: 20
                  minLength: 0
                retailerPhoneNumber:
                  type: string
                  pattern: '^[0-9]{6,}-[0-9]{4,}-[0-9]{4,}$'
                  description: 小売事業者担当者連絡先電話番号（市外局番-市内局番-加入者番号）
                abolishTime:
                  type: string
                  pattern: yyyyMMdd
                  description: 接続供給廃止年月日。廃止の予定年月日。（yyyyMMdd形式）
              required:
                - supplyPointNumber
                - retailerCode
                - retailerName
                - loginUserId
                - retailerStaff
                - retailerPhoneNumber
                - abolishTime
            examples:
              example-1:
                value:
                  supplyPointNumber: '0000111122223333444455'
                  retailerCode: '12345'
                  retailerName: テスト
                  loginUserId: '1234567890'
                  retailerStaff: biiiiip energe
                  retailerPhoneNumber: 000000-0000-0000
                  abolishTime: '20210301'
        description: Post the necessary fields for the API to create a new user.
      description: |-
        - Apply for switching service provided by octto.
        - Swith old electricity retailer to PIPI (abolish old and apply for new)
        - Submit application only, need check switching status through `Check switching status`.
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  referenceId:
                    type: string
                    description: ''
                  message:
                    type: object
                    properties:
                      applicationNumber:
                        type: string
                        description: 照会用申込番号
                    required:
                      - applicationNumber
                required:
                  - referenceId
              examples:
                example-1:
                  value:
                    referenceId: 12345-abcde-12abc-34def
                    message:
                      applicationNumber: '1234567890000'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  referenceId:
                    type: string
                    minLength: 1
                  message:
                    type: object
                    properties:
                      error:
                        type: string
                        minLength: 1
                    required:
                      - error
                required:
                  - referenceId
                  - message
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  referenceId:
                    type: string
                    minLength: 1
                  message:
                    type: object
                    properties:
                      error:
                        type: string
                        minLength: 1
                    required:
                      - error
                required:
                  - referenceId
                  - message
              examples:
                example-1:
                  value: {}
    parameters: []
  /switchingStatus:
    get:
      summary: Check switching status
      operationId: get-switching-status
      responses:
        '200':
          description: OK
      description: 'Check switching status through '
components:
  schemas: {}
